title: GUI Definition Language
description: GitHub landing page of the GUI Definition Language
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"